#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#   "https://{all}/": { type: upstream, upstream: "app:http" }
#   "https://{all}/": { type: upstream, upstream: "varnish:http", cache: { enabled: false } }
#   "http://{all}/": { type: redirect, to: "https://{all}/" }